version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - dev-net

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - dev-net

networks:
  dev-net:
    driver: bridge
